### ISSUE TITLE
Server crash on fast fly around the map (noclip)

### ISSUE THREAD

**Issue by Shionsan** [TaskaRaine/Ore-Crystals#9]
When flying around the map at fast speed (2+), eventually ending up with server going down with lots of these errors:

```
23.1.2022 10:42:42 [Error] GetBlockId(): Block with code 'orecrystals:orecrystals_crystal_bountiful-nativegold-ore_down' does not exist, defaulting to 0 for air
23.1.2022 10:42:42 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.ClassRegistryAPI.CreateEntity(EntityProperties entityType)
   at OreCrystals.BlockEntityCrystalObeliskSpawner.SpawnCrystalLocusts() in C:\Projects\vsmods\mods\orecrystals\src\blockentity\BECrystalObeliskSpawner.cs:line 100
   at OreCrystals.BlockEntityCrystalObeliskSpawner.CheckShouldSpawnHeart(Single dt) in C:\Projects\vsmods\mods\orecrystals\src\blockentity\BECrystalObeliskSpawner.cs:line 152
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.ServerMain.Process()
```

Can this be due to Ores'O'Plenty mod?

**Comment by TaskaRaine** [comment]
Yea probably :/

It looks like Ores'O'Plenty adds gold ore that's not hosted within quartz. I don't have crystals/locust variants set up to deal with that. I assume it has something to do with that.

**Comment by TaskaRaine** [comment]
Things definitely weren't playing nicely together. Although compatibility hasn't been added for any mod ores, Ore Crystals should now simply ignore them whenever they're present, in version 1.3.6 of the mod.

Thank you for bringing this to my attention ^.^
